### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by Quipyowert2** [hhirsch/ardentryst#5]
According to [PythonClock.org](https://pythonclock.org): "Python 2.7 will not be maintained past 2020." More specifically, Python 2 support is scheduled to end on [Jan 1, 2020](https://github.com/python/devguide/pull/344). Porting this to Python 3 might be a good idea.

I tried to port it to Python 3 myself (using `2to3`) but I couldn't figure out how to get Conch.py (the audio library for Ardentryst) to work in Python 3. Also, the game appears to have an obfuscated anti-cheat routine. I don't have enough experience with Python to figure out how to port that obfuscated function to Python 3.

EDIT: passing `-ns` as a command line option seems to make Ardentryst get past the `no available audio device` error that it was having. (I'm running it in Windows Subsystem for Linux; the audio doesn't work sometimes).

**Comment by eamanu** [comment]
I think this issue could be close becase #6 was merged
